run:
  timeout: 5m
  tests: false
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - text: "shadow: declaration of \"err\""
      linters:
        - govet

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
