# Конфигурация golangci-lint
# Это как "правила проверки" для твоего кода
version: "2"

run:
  timeout: 5m  # Максимальное время работы
  tests: false  # Не проверять тестовые файлы так строго

# Какие линтеры включить?
linters:
  enable:
    - govet         # Поиск подозрительных конструкций
    - staticcheck   # Множество проверок
    - unused        # Неиспользуемый код
    - ineffassign   # Неэффективные присваивания
    - misspell      # Опечатки в комментариях
    - gocyclo       # Сложность функций
    # - dupl        # Дублирование кода (отключено - для pet project OK)
  disable:
    - errcheck      # Запускается отдельно в CI
    - gosec         # Запускается отдельно в CI

# Настройки для конкретных линтеров
linters-settings:
  gocyclo:
    min-complexity: 25  # Максимальная сложность функции (увеличено для bot handlers)
  
  dupl:
    threshold: 100  # Минимум строк для определения дубликата
  
  errcheck:
    check-blank: false  # Разрешить игнорировать ошибки через _

# Какие файлы/папки пропустить?
issues:
  exclude-rules:
    # Разрешить длинные строки в тестах
    - path: _test\.go
      linters:
        - lll
    
    # Игнорировать некоторые ошибки в vendor
    - path: vendor/
      linters:
        - all
  
  # Не показывать эти конкретные ошибки
  exclude:
    - "G104: Errors unhandled"  # Иногда можно игнорировать ошибки
    - "G115: integer overflow conversion"  # We use safe bounds checking where needed
    - "Error return value of `a.sendResponse` is not checked"  # В panic handler это OK
    - "Error return value of `\\(\\*encoding/json.Encoder\\).Encode` is not checked"  # JSON encoding errors handled at HTTP level
    - "Error return value of `tx.Rollback` is not checked"  # Rollback in defer is OK
    - "Error return value of `b.Stop` is not checked"  # Shutdown already logged
    - "Error return value of `rows.Scan` is not checked"  # Database query errors handled separately
    - "Error return value of `\\(\\*database/sql.Row\\).Scan` is not checked"  # Scan errors handled at query level
    
  max-same-issues: 0  # Показывать все найденные проблемы
