version: "2"

run:
  timeout: 5m
  tests: false

linters:
  enable:
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - gocyclo
    - gosec
    - errcheck
  disable:
    - dupl

linters-settings:
  gocyclo:
    min-complexity: 15
  
  errcheck:
    check-blank: false
  
  gosec:
    severity: medium
    confidence: medium

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
